[package]
name = "ltv_derive"
version = "0.1.0"
authors = ["Sam Mackenzie <smackenzie@descartes.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ltv_derive"
proc-macro = true

[dependencies]
syn = "1"
quote = "1"
proc-macro2 = "1"


[dev-dependencies]
ltv = { version = "0.1", path = "../ltv" }
